### ISSUE TITLE
Implementar Sockets

### ISSUE THREAD

**Issue by kshmir** [kshmir/so-2011#6]

**Comment by kshmir** [comment]
Tira esto en ubuntu 11.04

> Starting transporter test
> It should be able to listen and write
> tp1_test: src/tps/tp1/tp1_test.c:75: networking_test: Assertion `cstring_compare(data,"cliente") == 0' failed.
> ./run_ubuntu: line 7: 12563 Aborted                 ./$1

Y esto en OSX.

> Starting transporter test
> bind call failed: Address family not supported by protocol family

**Beware!**

**Comment by kshmir** [comment]
Como viene esto? Necesitás ayuda? Que onda?

**Comment by maximovs** [comment]
Mira, estoy haciéndolo con udp ahora y creo q va bien asiq tranqui. Me voy a quedar esta noche, si tengo drama te aviso pero no creo q haya problemas. Un abrazo

Enviado desde mi iPhone

**Comment by kshmir** [comment]
No estaba ya hecho con UDP? Que onda?

**Comment by maximovs** [comment]
Estaba hecho tcp y udp. Me mate tratando de q me ande tcp pero siguió sinfuncar tonces me puse a pasar el udp para q pase el test, ni bien termine commiteo

Enviado desde mi iPhone

**Comment by kshmir** [comment]
Ok, abrazo.

**Comment by kshmir** [comment]
tratá de tenerlo para mañana, yo voy a terminar smem para mañana seguro. 

Cris

**Comment by kshmir** [comment]
Para cuando?? Van 2 semanas y pico...
