### ISSUE TITLE
Preparar Informe IPCs

### ISSUE THREAD

**Issue by kshmir** [kshmir/so-2011#8]

**Comment by amarseillan-zz** [comment]
Asd 
------Original Message------
From: kshmir
To: agustinmarseillan@gmail.com
Subject: [so-2011] Preparar Informe IPCs (#8)
Sent: Aug 22, 2011 09:06

## 

Reply to this email directly or view it on GitHub:
https://github.com/kshmir/so-2011/issues/8

Enviado desde mi BlackBerry de Movistar (http://www.movistar.com.ar)

**Comment by kshmir** [comment]
Cómo está esto?
Agregale marco teórico, arquitectura y las imágenes, no hay nada de eso en dropbox!!!

**Comment by kshmir** [comment]
Como viene el informe ? #2

**Comment by amarseillan-zz** [comment]
falta:
implementación MSGQUEUE
implementación SOCKETS
ver TO-DO's dentro del informe

**Comment by kshmir** [comment]
Como viene esto?
Mañana te mando un reporte rápido de cómo es el cleanexit y como terminamos el proceso.

**Comment by kshmir** [comment]
Con suerte tambien benchs :)
